FROM golang:alpine AS builder

RUN go env -w GO111MODULE=auto \
  && go env -w CGO_ENABLED=0

WORKDIR /build

RUN apk add --no-cache git \
    && git clone -b dev --single-branch https://github.com/Mrs4s/go-cqhttp.git \
    && cd go-cqhttp \
    && set -ex \
    && go build -ldflags "-s -w -extldflags '-static'" -o /build/cqhttp

FROM alpine:latest

COPY docker-entrypoint.sh /docker-entrypoint.sh

RUN chmod +x /docker-entrypoint.sh && \
    apk add --no-cache --update \
      ffmpeg \
      coreutils \
      shadow \
      su-exec \
      tzdata && \
    rm -rf /var/cache/apk/* && \
    mkdir -p /app && \
    mkdir -p /data && \
    mkdir -p /config && \
    useradd -d /config -s /bin/sh abc && \
    chown -R abc /config && \
    chown -R abc /data

ENV TZ="Asia/Shanghai"
ENV UID=99
ENV GID=100
ENV UMASK=002

COPY --from=builder /build/cqhttp /usr/bin/

WORKDIR /data

VOLUME [ "/data" ]

ENTRYPOINT [ "/docker-entrypoint.sh" ]
CMD [ "/usr/bin/cqhttp" ]