FROM alpine:latest

ENV TZ=Asia/Shanghai \
    LANG=C.UTF-8

COPY download /tmp/download/

RUN if [ "$(apk --print-arch)" = "x86_64" ]; then \
        MYARCH="amd64"; \
    elif [ "$(apk --print-arch)" = "aarch64" ]; then \
        MYARCH="arm64"; \
    elif [ "$(apk --print-arch)" = "armhf" ]; then \
        MYARCH="armv7"; \
    elif [ "$(apk --print-arch)" = "i386" ]; then \
        MYARCH="386"; \
    else \
        echo "Unknown architecture"; \
        exit 1; \
    fi \
    && echo $MYARCH \
    && apk add --no-cache tzdata ffmpeg && cd /tmp \
    && mv download/go-cqhttp_linux_$MYARCH /usr/bin/cqhttp \
    && cp /usr/share/zoneinfo/$TZ /etc/localtime \
    && chmod +x /usr/bin/cqhttp \
    && echo $TZ > /etc/timezone \
    && rm -rf /tmp/* /var/cache/apk/*

ENTRYPOINT [ "/usr/bin/cqhttp" ]