name: Docker-Build-dev

on:
  push:
    paths:
      - '.github\workflows\docker-image-dev.yml'
      - 'Dockerfile-dev'
      - 'devUrl.txt'

  # schedule:
  #   - cron: '12 3 * * *'  #每天一次

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: getDev
      run: |
        mkdir -p download
        while read -r url; do
          echo "下载文件：$url"
          final_url=$(curl -sLo /dev/null -w '%{url_effective}' $url)
          wget "$final_url" -P ./download/
        done < devUrl.txt
        find ./download -iname "*.zip" -print0 | while read -d $'\0' file
        do
          unzip -q "$file" -d "${file%.*}" && rm -f "$file"
        done
        ls ./download/

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile-dev
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
            ${{ secrets.DOCKER_USERNAME }}/gocqhttp:dev