name: Docker-Build-dev

on:
  push:
    branches:
      - main
    # paths:
    #   - '.github\workflows\docker-image-dev.yml'
    #   - 'Dockerfile-dev'

  schedule:
    - cron: '12 3 * * *'  #每天一次

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v2

    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}

    - name: getDev
      id: dev
      run: |
        sudo apt-get install jq -y
        LATEST_RUN_URL=$(curl -s 'https://api.github.com/repos/Mrs4s/go-cqhttp/actions/workflows/ci.yml/runs' | jq -r '.workflow_runs[0].html_url')
        echo $LATEST_RUN_URL

        ARTIFACTS=$(curl -s "${LATEST_RUN_URL}" | jq '.artifacts[] | select(.archive_download_url)')
        echo $ARTIFACTS

        if [ -n "${ARTIFACTS_URLS}" ]; then
          for artifact in ${ARTIFACTS}; do
          URL=$(echo "${artifact}" | jq -r '.archive_download_url')
          FILENAME=$(echo "${artifact}" | jq -r '.name')
          DOWNLOAD_URL="https://api.github.com${URL}"
          DOWNLOAD_LINK=$(curl -s --header "Authorization: Bearer ${{secrets.github}}" --header 'Accept: application/octet-stream' "${DOWNLOAD_URL}" | jq -r '.url')
          curl -sL --header "Authorization: Bearer ${{secrets.github}}" --header 'Accept: application/octet-stream' "${DOWNLOAD_LINK}" -o "${FILENAME}.zip"
          echo "url=true" >> GITHUB_OUTPUT
        done
        else
          echo "No Artifacts URLs found." >&2
          echo "url=false" >> GITHUB_OUTPUT
          exit 1
        fi

    - name: Login to DockerHub
      if: ${{ steps.dev.outputs.url == 'true' }}
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      if: ${{ steps.dev.outputs.url == 'true' }}
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile-dev
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
            ${{ secrets.DOCKER_USERNAME }}/gocqhttp:dev